//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveRoster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Player
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RegistrationNumber { get; set; }
        public decimal Weight { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Team { get; set; }
        public bool Coach { get; set; }
        public byte[] Image { get; set; }
    
        public virtual tbl_Team tbl_Team { get; set; }
    }
}
